### ISSUE TITLE
Version not correct

### ISSUE THREAD

**Issue by fabianschwarzfritz** [reviewninja/www.review.ninja#36]
Hi @dfarr ,
seems like the version of review ninja is not displayed correctly on the website. I get attached screenshot as output with safari, as well als chrome. The displayed version is "0.0.0".
Cheers,
Fabian
![screen shot 2016-08-15 at 17 04 09](https://cloud.githubusercontent.com/assets/1759672/17668656/a3da34e8-630a-11e6-96be-e6d6c60dd51f.png)

**Comment by fabianschwarzfritz** [comment]
Hmm, seems to work fine now, maybe a temporary problem on my machine.

**Comment by dfarr** [comment]
It's flaky for sure! But perhaps not that big of a deal 😋
